version: 2
jobs:
  build:
    docker:
      - image: klamping/wdio-ff
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test