version: 2.0
jobs:
  build:
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - run:
        name: install-npm
        command: npm install
    - run:
        name: test
        command: npm run test
    - store_test_results:
        path: ./test-results.xml
    - store_artifacts:
        path: ./test-results.xml
    - run:
      name: upload to 
      command: curl -X POST --header "Content-Type:text/xml" --header "x-api-key:${CALLIOPE_API_KEY}" --form "file[]=@test-results.xml" "https://app.calliope.pro/api/v2/profile/542/report/import/junit?os=node"
workflows:
  version: 2
  nightly:
    triggers:
    - schedule:
        cron: "16 14 * * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - build
  build_and_test:
    jobs:
    - build