version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm run test
      - store_test_results:
          path: mochawesome-report/
      - store_artifacts:
          path: mochawesome-report/webdriverio-template-result.html
workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build